print("int demo started...")
print("int by default decimals 10=", end='')
print(10)
print("binary integer 0b10=",end='')
print(0b10)
print("octal integer 0o10=",end='')
print(0o10)
print("hexa decimal integer 0x10=",end='')
print(0x10)
print("int() constructors")
print("int(3)=",end='')
print(int(3))
print("int from float int(3.5)=",end='')
print(int(3.5))
print("int from string int('312')=",end='')
print(int('312'))
print("int from base number int('1001',3)=",end='')
print(int('1001',3))
print("int demo completed...")
print("\n ==================================\n")

print("float demo started...")
print("3.125 = ",end='')
print(3.125)
print("3e8 = ",end='')
print(3e8)
print("float from int float(5) = ",end='')
print(float(5))
print("float from string float('1.618') = ",end='')
print(float(1.618))
print("float from not a number flaot('nan')=",end='')
print(float('nan'))
print("float demo completed...")

print("\n ==================================\n")

print("None demo started...")
print("None=",end='')
print(None)
print("None assignment and equality a=None a is None=",end='')
a=None
print(a is None)
print("None demo completed...")


print("\n ==================================\n")

print("True = ",end='')
print(True)
print("False = ",end='')
print(False)
print("bool constructors ... ")
print("bool from int bool(0) = ",end='')
print(bool(0))
print("bool from int bool(45) = ",end='')
print(bool(45))
print("bool from float bool(0.0) = ",end='')
print(bool(0.0))
print("bool from float bool(0.2314) = ",end='')
print(bool(0.2314))
print("bool from str bool('') = ",end='')
print(bool(''))
print("bool from str bool('hello') = ",end='')
print(bool('hello'))
print("bool from collection bool([]) = ",end='')
print(bool([]))
print("bool from collection bool([1,2,4]) = ",end='')
print(bool([1,2,4]))
